// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFCgRpGlNlEClRqSY_fvGoQcaEVErHoiU',
    appId: '1:339366330932:android:f60227cab6a59dbbdf4061',
    messagingSenderId: '339366330932',
    projectId: 'lamie-middle-east',
    storageBucket: 'lamie-middle-east.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHd3Yzx6-8JZRVexpem1Ra1jqeVzszvZM',
    appId: '1:339366330932:ios:7d27f8c7db9e7f6ddf4061',
    messagingSenderId: '339366330932',
    projectId: 'lamie-middle-east',
    storageBucket: 'lamie-middle-east.appspot.com',
    androidClientId: '339366330932-a0itj3ha3ag0mk3ft1p5imtjup8kqin6.apps.googleusercontent.com',
    iosClientId: '339366330932-te6k6t27dr855lao6l508ovlotch33if.apps.googleusercontent.com',
    iosBundleId: 'com.example.lamieMiddleEast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Co9hemGM6rD7p-dZSHQJMP8EUzzBbOo',
    appId: '1:339366330932:web:f4449eddf8100948df4061',
    messagingSenderId: '339366330932',
    projectId: 'lamie-middle-east',
    authDomain: 'lamie-middle-east.firebaseapp.com',
    storageBucket: 'lamie-middle-east.appspot.com',
  );
}
